apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbitmq
  template:
    metadata:
      labels:
        components: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.34
          ports:
            - containerPort: 5672
          env:
            - name: SEED_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: SEED_USERNAME
            - name: SEED_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: SEED_USER_PASSWORD
          resources:
            limits:
              memory: "1Gi"
              cpu: "300m"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc