appName: conv

app:
  name: conv-app
  image: antonlarichev/conv-app
  version: "1.2"
  port: 80
  components: frontend
  replicas: 1
  limits:
    memory: "512Mi"
    cpu: "300m"
  config:
    name: app-config
    data:
      VITE_DOMAIN: ""
  env:
    name: VITE_DOMAIN

api:
  name: conv-api
  image: antonlarichev/conv-api
  version: "1.0"
  port: 3000
  components: backend
  replicas: 1
  limits:
    memory: "512Mi"
    cpu: "300m"
  env:
    - name: AMQP_EXCHANGE
      key: AMQP_EXCHANGE
    - name: AMQP_USER
      key: SEED_USERNAME
    - name: AMQP_PASSWORD
      key: SEED_USER_PASSWORD
    - name: AMQP_HOSTNAME
      key: AMQP_HOSTNAME
  pvc:
    storage: 1Gi
    accessMode: ReadWriteOnce

conv:
  name: conv-conv
  image: antonlarichev/conv-service
  version: "1.0"
  port: 4000
  components: converter
  replicas: 1
  limits:
    memory: "512Mi"
    cpu: "300m"
  env:
    - name: AMQP_EXCHANGE
      key: AMQP_EXCHANGE
    - name: AMQP_USER
      key: SEED_USERNAME
    - name: AMQP_PASSWORD
      key: SEED_USER_PASSWORD
    - name: AMQP_HOSTNAME
      key: AMQP_HOSTNAME
    - name: AMQP_QUEUE
      key: AMQP_QUEUE
  pvc:
    storage: 1Gi
    accessMode: ReadWriteOnce

rabbitmq:
  name: rabbitmq
  image: rabbitmq
  version: "3.8.34"
  port: 5672
  components: rabbitmq
  replicas: 1
  limits:
    memory: "1Gi"
    cpu: "300m"
  env:
    - name: RABBITMQ_DEFAULT_USER
      key: SEED_USERNAME
    - name: RABBITMQ_DEFAULT_PASS
      key: SEED_USER_PASSWORD
  pvc:
    storage: 512Mi
    accessMode: ReadWriteOnce

ingress:
  name: myingress
  host: conv.test
  app:
    path: "/"
    port:
      number: 80
  api:
    path: "/api"
    port:
      number: 3000
  conv:
    path: "/uploads"
