apiVersion: apps/v1
kind: Deployment
metadata: 
  name: conv-conv-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      components: converter
  template:
    metadata:
      labels:
        components: converter
    spec:
      containers:
        - name: conv-conv
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 4000
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: SEED_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: AMQP_HOSTNAME
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: AMQP_QUEUE
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - name: conv-data
              mountPath: /opt/app/uploads
      volumes:
        - name: conv-data
          persistentVolumeClaim:
            claimName: conv-pvc