apiVersion: apps/v1
kind: Deployment
{{- with .Values.app }}
metadata: 
  name: {{ .name }}-deployment
spec:
  {{- include "deploymentSpec.template" . | indent 2}}
    spec:
      containers:
        {{- include "containerMetadata.template" . | indent 8}}
          resources:
            limits: {{ .limits | toYaml | nindent 14 }}
          env:
            - name: {{ .env.name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .config.name }}
                  key: {{ .env.name }}
{{- end }}