apiVersion: v1
kind: Secret
{{- with .Values.secret }}
metadata:
  name: {{ $.Values.appName }}-secret
type: Opaque
stringData:
  SEED_USERNAME: {{ .user }}
  SEED_USER_PASSWORD: {{ .pass }}
  AMQP_EXCHANGE: {{ .exchange }}
  AMQP_HOSTNAME: "{{ $.Values.rabbitmq.name }}-clusterip"
  AMQP_QUEUE: {{ .queue }}
{{- end}}