apiVersion: networking.k8s.io/v1
kind: Ingress
{{- with .Values.ingress}}
metadata:
  name: {{ .name }}
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - host: {{ .host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .app.path }}
        backend:
          service:
            name: {{ $.Values.app.name }}-clusterip
            port: {{ .app.port | toYaml | nindent 14}}
      - pathType: Prefix
        path: {{ .api.path }}
        backend:
          service:
            name: {{ $.Values.api.name }}-clusterip
            port: {{ .api.port | toYaml | nindent 14}}
      - pathType: Prefix
        path: {{ .conv.path }}
        backend:
          service:
            name: {{ $.Values.api.name }}-clusterip
            port: {{ .api.port | toYaml | nindent 14}}
{{- end }}